# -*- coding: utf-8 -*-
"""LC1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1orl7yoq9o3fF1IYnfyTA14JvIEYujfC0
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Read the CSV file iris.csv
import pandas as pd
df = pd.read_csv ("https://raw.githubusercontent.com/syttt001/pgss-2022-cs-lab1/main/iris.csv", header=None)
df.columns = ['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width', 'Class']
df

df.info()

